remote_theme: "mmistakes/jekyll-theme-basically-basic"
title: "A Basic Guide to Reproducible Research"

markdown: kramdown

author:
  name: Stefan Binder

github_username: binste
linkedin_username: stefan-binder-36b013130